version: '3.9'

services:
  api:
    image: node:alpine
    container_name: api
    networks:
      - demo
    command: npm start
    working_dir: /usr/src/app
    ports:
      - 3333:3000
    volumes:
      - ./api:/usr/src/app

networks:
  demo:
    driver: bridge
